config/routes.rb
Rails.application.routes.draw do
   root 'homes#top'
  resources :tools
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tool.rb
class Tool < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
   def index
    @tools = Tool.all
    @tool = Tool.new
   end

  def create

     @tool = Tool.new(tool_params)

    if @tool.save
      flash[:notice] = "Tool was successfully created"
      redirect_to tool_path(@tool.id)
    else
      @tools = Tool.all
      render :index
    end

  end

  def index
    @tools = Tool.all
    @tool = Tool.new
  end

  def show
    @tool = Tool.find(params[:id])
  end

  def edit
     @tool = Tool.find(params[:id])
  end

  def update
    @tool = Tool.find(params[:id])
    if @tool.update(tool_params)
      flash[:notice] = "Took was successfully created"
      redirect_to tool_path(@tool.id)
    else
      render :edit
    end



  end

  def destroy
    tool =Tool.find(params[:id])  # データ（レコード）を1件取得
    tool.destroy  # データ（レコード）を削除
    redirect_to '/tools'  # 投稿一覧画面へリダイレクト


  end
   private
  # ストロングパラメータ
  def tool_params
    params.require(:tool).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/homes/top.html.erb
<h1>ようこそ
  <strong>spotool</strong>
  へ!
  </h1>
  <p>
  <strong>spotool</strong>
  では、様々なスポーツ製品に関するあなたの意見や
  </p>
  <p>印象を共有することができます</p>
  <span><%= link_to "start", "/tools"  %></span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spotools</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tools/edit.html.erb
<h1>Editing tool</h1>
<% if @tool.errors.any? %>
  <%= @tool.errors.count %>件のerrorが発生しました
  <ul>
    <% @tool.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
<%= form_with model: @tool do |f| %>

  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>本文</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Update Tool' %>

<% end %>
<span><%= link_to "show", tool_path(@tool.id)%></span>
<span><%= link_to "back", tools_path(@tool.id)%></span>

app/views/tools/index.html.erb
<h1>spotool</h1>
<% if @tool.errors.any? %>
  <%= @tool.errors.count %>件のerrorが発生しました
  <ul>
    <% @tool.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<table>
  <thead>
    <tr>
      <th>Title </th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
       <% @tools.each do |tool| %>
       <tr>
         <td><%= tool.title %></td>
         <td><%= tool.body %></td>
         <td><%= link_to "show", tool_path(tool.id)%></td>
         <td><%= link_to "edit", edit_tool_path(tool.id)%></td>
         <td><%= link_to "delete", tool_path(tool.id), method: :delete, "data-confirm" => "Are you sure？" %>></td>
       </tr>
       <% end %>
    </tbody>
</table>
<h2>New tool</h2>


<!-- 新しい投稿フォーム -->
<%= form_with model: @tool, url: tools_path, local: true do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Tool' %>
  </div>
<% end %>

app/views/tools/show.html.erb
<h2>title</h2>
<p><%= @tool.title %></p>

<h2>body</h2>
<p><%= @tool.body %></p>
<span><%= link_to "edit", edit_tool_path(@tool.id)%></span>
<span><%= link_to "back", tools_path(@tool.id)%></span>